load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Logging",
    module_name = "Logging",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
       
    ],
    visibility = [
        "//visibility:public",
    ],
)
